### ISSUE TITLE
thread 'main' panicked at 'range end index 422 out of range for slice of length 421', src/main.rs:228:31 (Client project)

### ISSUE THREAD

**Issue by supersolera** [0xNineteen/solana-arbitrage-bot#6]
Hi!

I can't execute with success the instruction: cargo run --bin main -- --cluster mainnet
Then compiling I get this error:

thread 'main' panicked at 'range end index 422 out of range for slice of length 421', src/main.rs:228:31

What can be done to fix this error?
Thanks!

**Comment by alanwu4321** [comment]
Got the same error as well
